---
name: Perl6-Pod
version: 0.01_02
author:
  - Zahatski Aliaksandr zag@cpan.org
abstract: use Perl6's pod in perl5 programms
license: perl
resources:
  license: ~
requires:
  Encode: 0
  XML::ExtOn: 0
  XML::Parser: 0
  XML::SAX::Writer: 0
  XML::Writer: 0
provides:
  Perl6::Pod:
    file: lib/Perl6/Pod.pm
    version: 0.01_02
  Perl6::Pod::Block:
    file: lib/Perl6/Pod/Block.pm
  Perl6::Pod::Block::comment:
    file: lib/Perl6/Pod/Block/comment.pm
  Perl6::Pod::Directive::config:
    file: lib/Perl6/Pod/Directive/config.pm
  Perl6::Pod::Directive::use:
    file: lib/Perl6/Pod/Directive/use.pm
  Perl6::Pod::FormattingCode:
    file: lib/Perl6/Pod/FormattingCode.pm
  Perl6::Pod::Parser:
    file: lib/Perl6/Pod/Parser.pm
  Perl6::Pod::Parser::Context:
    file: lib/Perl6/Pod/Parser/Context.pm
  Perl6::Pod::Parser::Pod2Events:
    file: lib/Perl6/Pod/Parser/Pod2Events.pm
  Perl6::Pod::To:
    file: lib/Perl6/Pod/To.pm
  Perl6::Pod::To::XML:
    file: lib/Perl6/Pod/To/XML.pm
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
