---
name: Perl6-Pod
version: 0.02_01
author:
  - Zahatski Aliaksandr zag@cpan.org
abstract: use Perl6's pod in perl5 programms
license: perl
resources:
  license: ~
requires:
  Encode: 0
  Getopt::Long: 0
  Pod::Usage: 0
  XML::ExtOn: 0
  XML::Flow: 0
  XML::Parser: 0
  XML::SAX::Writer: 0
  XML::Writer: 0
provides:
  Perl6::Pod:
    file: lib/Perl6/Pod.pm
    version: 0.02_01
  Perl6::Pod::Block:
    file: lib/Perl6/Pod/Block.pm
  Perl6::Pod::Block::comment:
    file: lib/Perl6/Pod/Block/comment.pm
  Perl6::Pod::Directive::config:
    file: lib/Perl6/Pod/Directive/config.pm
  Perl6::Pod::Directive::use:
    file: lib/Perl6/Pod/Directive/use.pm
  Perl6::Pod::FormattingCode:
    file: lib/Perl6/Pod/FormattingCode.pm
  Perl6::Pod::FormattingCode::M:
    file: lib/Perl6/Pod/FormattingCode/M.pm
  Perl6::Pod::Parser:
    file: lib/Perl6/Pod/Parser.pm
  Perl6::Pod::Parser::AddHeadLevels:
    file: lib/Perl6/Pod/Parser/AddHeadLevels.pm
  Perl6::Pod::Parser::AddIds:
    file: lib/Perl6/Pod/Parser/AddIds.pm
  Perl6::Pod::Parser::Context:
    file: lib/Perl6/Pod/Parser/Context.pm
  Perl6::Pod::Parser::CustomCodes:
    file: lib/Perl6/Pod/Parser/CustomCodes.pm
  Perl6::Pod::Parser::ListLevels:
    file: lib/Perl6/Pod/Parser/ListLevels.pm
  Perl6::Pod::Parser::Pod2Events:
    file: lib/Perl6/Pod/Parser/Pod2Events.pm
  Perl6::Pod::To:
    file: lib/Perl6/Pod/To.pm
  Perl6::Pod::To::DocBook:
    file: lib/Perl6/Pod/To/DocBook.pm
  Perl6::Pod::To::DocBook::ProcessHeads:
    file: lib/Perl6/Pod/To/DocBook/ProcessHeads.pm
  Perl6::Pod::To::Mem:
    file: lib/Perl6/Pod/To/Mem.pm
  Perl6::Pod::To::XML:
    file: lib/Perl6/Pod/To/XML.pm
  Test::Filter:
    file: lib/Perl6/Pod/To/DocBook.pm
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
